version: '3'

services:
  app:
    image: ghcr.io/u6k/investment-local-horse-racing-crawler:1.8.1
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - ./.env
    volumes:
      - ${DOCKER_VOLUMES}/local-horse-racing-crawler/db:/var/lib/postgresql/data
      - ${DOCKER_VOLUMES}/local-horse-racing-crawler/wal_archive:/archive
    restart: always

networks:
  default:
    external:
      name: production
