# -*- mode: ruby -*-

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.network :forwarded_port, host: 10080, guest: 80, id: "http"
  config.vm.network :forwarded_port, host: 10443, guest: 443, id: "https"
  config.vm.network :forwarded_port, host: 10022, guest: 22, id: "ssh"

  config.disksize.size = "10GB"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 4192
  end

  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "provisioning/debian-for-docker.yml"
  #  ansible.inventory_path = "provisioning/hosts"
  #  ansible.limit = 'all'
  #end
end
